"""Added created_on and updated_on columns to recipes table

Revision ID: 541cadca20da
Revises: f4a27f9487d2
Create Date: 2021-04-10 17:35:47.383970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "541cadca20da"
down_revision = "f4a27f9487d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("created_on", sa.DateTime(), nullable=True))
    op.add_column("recipes", sa.Column("updated_on", sa.DateTime(), nullable=True))
    op.execute("UPDATE recipes SET created_on = CURRENT_DATE;")
    op.execute("UPDATE recipes SET updated_on = CURRENT_DATE;")
    op.alter_column("recipes", "created_on", nullable=False)
    op.alter_column("recipes", "updated_on", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "updated_on")
    op.drop_column("recipes", "created_on")
    # ### end Alembic commands ###
